import Link from 'next/link'
export default function HomePage() {
  return (
    <>
      <section className="relative text-center py-16 md:py-24 px-4 md:px-8 lg:px-20 overflow-hidden">
        <div className="absolute inset-0 bg-grid-pattern opacity-30 pointer-events-none" />
        <div className="absolute top-[-100px] left-1/2 -translate-x-1/2 w-[800px] h-[500px] bg-[radial-gradient(ellipse,rgba(0,198,184,0.1),transparent_65%)] pointer-events-none" />
        <div className="relative z-10 max-w-4xl mx-auto">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-accent/35 bg-accent/10 mb-7"><div className="w-1.5 h-1.5 rounded-full bg-accent animate-blink" /><span className="text-xs text-accent">AI-Powered Brain MRI Platform</span></div>
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-extrabold tracking-tighter leading-tight mb-5">Upload a scan.<br /><span className="text-accent block">Get answers.</span></h1>
          <p className="text-sm md:text-base text-muted leading-relaxed max-w-2xl mx-auto mb-11 px-4">CuraVision uses U-Net segmentation and Grad-CAM heatmaps to analyze brain MRI scans - then connects patients with verified neurologists.</p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-10"><Link href="/register" className="px-8 md:px-10 py-3.5 bg-accent text-[#050B18] rounded-lg text-sm md:text-base font-bold text-center hover:bg-[#00ddd4] transition">I'm a Patient</Link><Link href="/register" className="px-8 md:px-10 py-3.5 bg-transparent text-white border border-white/20 rounded-lg text-sm md:text-base text-center hover:border-blue hover:text-blue transition">I'm a Doctor</Link></div>
          <div className="flex flex-wrap gap-2 justify-center">{['U-Net Segmentation', 'Grad-CAM Heatmaps', 'LLM Reports', 'RAG Chatbot', 'DICOM Viewer'].map((chip) => (<span key={chip} className="flex items-center gap-1.5 px-3 md:px-4 py-1.5 rounded-full border border-border text-xs text-muted bg-card/70 font-mono"><span className="text-[10px] text-accent">▸</span>{chip}</span>))}</div>
        </div>
      </section>
      <section className="py-16 md:py-20 px-4 md:px-8 lg:px-20 bg-surface/30">
        <div className="text-center mb-12"><div className="text-[11px] tracking-[3px] uppercase text-accent font-semibold mb-3">How it works</div><h2 className="text-2xl md:text-3xl font-extrabold tracking-tight mb-3">From scan to report in 4 steps</h2></div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-px bg-border rounded-2xl overflow-hidden max-w-6xl mx-auto">
          {[{ icon: '📤', num: '01', title: 'Upload DICOM scan', desc: 'Patient uploads a brain MRI file. Rendered instantly in DICOM viewer.', tag: 'Cornerstone.js', color: 'accent' }, { icon: '🧠', num: '02', title: 'AI segmentation runs', desc: 'U-Net generates tumor mask. Grad-CAM highlights focus areas.', tag: 'U-Net + Grad-CAM', color: 'blue' }, { icon: '📝', num: '03', title: 'Draft report generated', desc: 'Local LLM drafts a structured radiology report - private, no cloud.', tag: 'LLM · Ollama', color: 'purple' }, { icon: '✅', num: '04', title: 'Doctor reviews & signs', desc: 'Doctor edits, approves, and publishes. Full audit trail.', tag: 'RBAC · Audit log', color: 'warn' }].map((step) => (
            <div key={step.num} className="bg-card p-6 md:p-8 relative"><div className="flex items-start justify-between mb-5"><div className={`w-12 h-12 rounded-xl flex items-center justify-center text-2xl bg-${step.color}/12 border border-${step.color}/25`}>{step.icon}</div><div className="font-mono text-2xl md:text-3xl font-medium text-sub">{step.num}</div></div><h3 className="text-base md:text-lg font-bold mb-3">{step.title}</h3><p className="text-xs md:text-[13px] text-muted leading-relaxed mb-4">{step.desc}</p><span className={`inline-flex px-3 py-1 rounded text-[11px] font-mono bg-${step.color}/10 text-${step.color} border border-${step.color}/20`}>{step.tag}</span><div className={`absolute bottom-0 left-6 md:left-8 right-6 md:right-8 h-0.5 rounded-full bg-gradient-to-r from-${step.color} to-transparent opacity-70`} /></div>
          ))}
        </div>
      </section>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 max-w-6xl mx-auto px-4 md:px-8 lg:px-20 py-16 md:py-20">
        <div className="bg-card border border-border rounded-2xl p-6 md:p-8 flex flex-col gap-4 hover:border-accent transition"><div className="inline-flex px-3.5 py-1 rounded-full bg-accent/8 border border-accent/20 text-accent text-[11px] font-semibold w-fit">For Patients</div><h3 className="text-xl font-extrabold">Your MRI, explained clearly</h3><p className="text-[13px] text-muted leading-relaxed">Upload your scan, receive an AI-analyzed report, book a specialist, and track your appointments.</p><div className="flex flex-col gap-2">{['DICOM scan upload and viewer', 'AI report access after doctor sign-off', 'Book verified neurologists'].map(f => (<div key={f} className="flex items-center gap-2 text-[13px] text-muted"><div className="w-1.5 h-1.5 rounded-full bg-accent" />{f}</div>))}</div><Link href="/register" className="mt-1.5 px-6 py-3 bg-accent text-[#050B18] rounded-lg text-sm font-bold w-fit text-center hover:bg-[#00ddd4] transition">Register as Patient</Link></div>
        <div className="bg-card border border-border rounded-2xl p-6 md:p-8 flex flex-col gap-4 hover:border-blue transition"><div className="inline-flex px-3.5 py-1 rounded-full bg-blue/8 border border-blue/20 text-blue text-[11px] font-semibold w-fit">For Doctors</div><h3 className="text-xl font-extrabold">AI that assists, not replaces</h3><p className="text-[13px] text-muted leading-relaxed">Review AI-generated masks, edit draft reports, manage patients with full audit trail.</p><div className="flex flex-col gap-2">{['Review U-Net masks and Grad-CAM', 'Edit and approve LLM-drafted reports', 'Full audit log on all actions'].map(f => (<div key={f} className="flex items-center gap-2 text-[13px] text-muted"><div className="w-1.5 h-1.5 rounded-full bg-blue" />{f}</div>))}</div><Link href="/register" className="mt-1.5 px-6 py-3 bg-blue text-[#050B18] rounded-lg text-sm font-bold w-fit text-center hover:bg-[#6fa0ff] transition">Register as Doctor</Link></div>
      </div>
    </>
  )
}