name: Debug VM
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Debug
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            sudo chmod 644 /opt/curavision/nginx/certs/curavision.*
            cd /opt/curavision && docker compose -f docker-compose.yml -f docker-compose.prod.yml restart proxy
